name: CD

on: [push, pull_request]

jobs:
  artifact:
    name: Publish Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            configs
            scripts
            src
            CHANGELOG.md
            LICENSE
            README.md
            client.lua
            fxmanifest.lua
            package.json
            pnpm-lock.yaml
            pnpm-workspace.yaml
            tsconfig.json
          sparse-checkout-cone-mode: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Post-build
        shell: bash
        run: |
          rm -rf ./.git
          rm -rf ./build
          rm -rf ./configs
          rm -rf ./node_modules
          rm -rf ./scripts
          rm -rf ./src
          rm -rf ./.yarn.installed
          rm -rf ./package.json
          rm -rf ./pnpm-lock.yaml
          rm -rf ./pnpm-workspace.yaml
          rm -rf ./tsconfig.json

          mkdir ../d4_devutils-out
          mv -v * ../d4_devutils-out/
          mv -v ../d4_devutils-out/ ./d4_devutils/

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: d4_devutils
          path: |
            ./*

  release:
    name: Draft Release
    runs-on: ubuntu-latest
    needs: artifact
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v6

      - name: Archive
        shell: bash
        run: |
          zip -r d4_devutils.zip ./d4_devutils

      - name: Draft release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            ./*.zip
